// lib/manual.mjs → docs/MANUAL.md
//
// The manual is written once, in lib/manual.mjs, and read in three places: the
// printable page at /manual, this markdown file for anyone reading the repo,
// and (later) the help panel inside the app. Only the first is hand-written;
// everything else is generated, because prose copied by hand drifts silently
// and the wrong copy is always the one someone is reading.
//
// Run:  node scripts/build-manual.mjs        (also runs on predev/prebuild)
// test/manual.test.mjs regenerates it in memory and fails if the committed
// file has fallen behind — so a forgotten build cannot ship a stale manual.
import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { fileURLToPath, pathToFileURL } from 'node:url'
import path from 'node:path'
import { SCREENS, screensOf, manualProgress } from '../lib/manual.mjs'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const OUT = path.join(ROOT, 'docs/MANUAL.md')

const bullets = (rows) => rows.map(([a, b]) => `- **${a}** — ${b}`).join('\n')

function section(s) {
  const out = [`### ${s.name}${s.path ? ` — \`${s.path}\`` : ''}`, '', s.what, '']
  if (s.status === 'draft') {
    out.push('> Not written out in full yet — the sentence above is all this entry promises.', '')
    return out.join('\n')
  }
  if (s.parts.length) out.push('**On the screen**', '', bullets(s.parts), '')
  if (s.dialogs.length) out.push('**Boxes that open on top of it**', '', bullets(s.dialogs), '')
  if (s.rules.length) out.push('**Rules that bite here**', '', s.rules.map(r => `- ${r}`).join('\n'), '')
  if (s.wrong.length) out.push('**When it goes wrong**', '', bullets(s.wrong), '')
  return out.join('\n')
}

export function manualMarkdown(screens = SCREENS) {
  const { total, written, drafts } = manualProgress(screens)
  const staff = screensOf('staff', screens)
  const pub = screensOf('public', screens)
  const contents = (list) => list.map(s => `- ${s.name} — ${s.what}`).join('\n')

  return `# The Kosher Connect manual

<!-- GENERATED FROM lib/manual.mjs — DO NOT EDIT THIS FILE.
     Edit the screen entries in lib/manual.mjs and run: node scripts/build-manual.mjs
     test/manual.test.mjs fails if this file is out of date. -->

Every screen in the system, what it is for, and what to do when it argues with
you. The step-by-step "how do I…" answers live inside the app — press **❓ How
do I…?** on any screen — and the numbers (rates, free days, caps) live in
BUSINESS_RULES.md and in Settings, never here, so there is only ever one price
list.

**${written} of ${total} screens written out in full${drafts ? `; ${drafts} still short entries` : ''}.**

---

## The staff app

${contents(staff)}

${staff.map(section).join('\n---\n\n')}

---

## Pages with their own address

${contents(pub)}

${pub.map(section).join('\n---\n\n')}
`
}

// Writes ONLY when run as a command. The freshness test imports this file to
// compare what the manual SHOULD say against what is committed — and while the
// write was a top-level side effect, that import quietly rewrote the file
// first, so the test compared the fresh copy with itself and passed on a stale
// manual every time. An import must be pure or the check it feeds is theatre.
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const md = manualMarkdown()
  const prev = existsSync(OUT) ? readFileSync(OUT, 'utf8') : null
  if (prev !== md) {
    writeFileSync(OUT, md)
    const { written, total } = manualProgress()
    console.log(`MANUAL.md: ${written}/${total} screens written → docs/MANUAL.md`)
  }
}
